# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CNPVhDFR-1bHAHAxciS3qYUsFSCmcrH
"""

!pip install -q google-genai

import json
from datetime import datetime , timedelta
import random
import os
from google import genai  # Call Client API from google genai library
from google.colab import userdata # fetch keys from colab interface
from google.genai import types # config return type of API

API_KEY=userdata.get('test')
MODEL= "gemini-2.5-flash"
client = genai.Client(api_key = API_KEY)

import requests
from datetime import datetime, timedelta

import requests
def flights_search_v2(origin: str, destination: str,outbound_date : str,return_date: str) -> str:
  # Get SerpAPI key from Colab secrets
  SERPAPI_API_KEY = userdata.get('serpapi')
  if not SERPAPI_API_KEY:
    return json.dumps({"error": "SERPAPI_API_KEY not found in Colab secrets. Please add it with the name 'SERPAPI_API_KEY'."})

  # SerpAPI endpoint for Google Flights
  SERPAPI_URL = "https://serpapi.com/search" # Corrected URL

  params = {
      "engine": "google_flights",
      "departure_id": origin, # Origin airport code (e.g., "PNQ")
      "arrival_id": destination, # Destination airport code (e.g., "BOS")
      "outbound_date" : outbound_date,
      #"return_date": return_date,
      "api_key": SERPAPI_API_KEY,
      "hl": "en", # Host language
      "gl": "us", # Geographic location
      "type":"2"
  }

  try:
    response = requests.get(SERPAPI_URL, params=params)
    response.raise_for_status() # Raise an exception for HTTP errors
    search_results = response.json()
    print(len(search_results) , type(search_results))
    for i in search_results:
      print(i)
    print("*"*50)
   # print("Best flights: ",search_results['best_flights'])
    print("+"*50)

    flights_data = []
    flight_options = []

    # SerpAPI's Google Flights results can be under 'best_flights' or 'other_flights'
    #if 'best_flights' in search_results:
    #    flight_options.extend(search_results['best_flights'])
    if 'other_flights' in search_results:
        flight_options.extend(search_results['other_flights'])

    if flight_options:
        for flight in flight_options:
            if 'flights' in flight and flight['flights']:
                first_leg = flight['flights'][0] # Get details of the first leg of the flight
                departure_time = first_leg.get('departure_airport', {}).get('time')
                airline = first_leg.get('airline')
                flight_number = first_leg.get('flight_number')
                price = flight.get('price')

                if departure_time and price: # Ensure essential data exists
                    flight_info = {
                        "flight": f"{airline} {flight_number}" if airline and flight_number else "N/A Flight",
                        "price": price,
                        "time": departure_time
                    }
                    flights_data.append(flight_info)

        if flights_data:
            return json.dumps(flights_data) # Return all found flights in the desired format
        else:
            return json.dumps({"error": "No detailed flight information could be extracted from SerpAPI response."})
    #else:
    return json.dumps({"error": "No flight data found in SerpAPI response for the given route."})

  except requests.exceptions.RequestException as e:
    return json.dumps({"error": f"API request failed: {e}. Please ensure the SerpAPI key is correct and origin/destination IDs are valid (e.g., 'PNQ' for Pune, 'BOS' for Boston)."})
  except json.JSONDecodeError:
    return json.dumps({"error": "Failed to decode JSON response from SerpAPI. Check API key and response format."})
  except Exception as e:
    return json.dumps({"error": f"An unexpected error occurred: {e}"})


print(flights_search_v2("PNQ", "PNQ","2026-06-23","2026-06-23"))





def hotels_search_v2(location: str, check_in_date: str, nights: int) -> str:
  SERPAPI_API_KEY = userdata.get('serpapi')
  if not SERPAPI_API_KEY:
    return json.dumps({"error": "SERPAPI_API_KEY not found in Colab secrets. Please add it with the name 'test'."})

  SERPAPI_URL = "https://serpapi.com/search"
    # Calculate check_out_date from check_in_date and nights
  try:
    check_in = datetime.strptime(check_in_date, "%Y-%m-%d")
    check_out = check_in + timedelta(days=nights)
    check_out_date = check_out.strftime("%Y-%m-%d")
  except ValueError:
    return json.dumps({"error": "Invalid date format for check_in_date. Please use YYYY-MM-DD."})
  params = {
      "engine": "google_hotels",
      "q": f"hotels in {location}",
      "check_in_date": check_in_date,
      "check_out_date": check_out_date,
      "api_key": SERPAPI_API_KEY,
      "hl": "en",
      "gl": "us",
  }
  try:
    response = requests.get(SERPAPI_URL, params=params)
    response.raise_for_status()
    search_results = response.json()
    print("SerpAPI Raw Search Results:", search_results) # Debug print

    hotels_data = []
    if 'properties' in search_results:
        for hotel in search_results['properties']:
            name = hotel.get('name')
            rating = hotel.get('overall_rating')
            price = hotel.get('price')
            if name and rating and price:
                hotels_data.append({"name": name, "rating": rating, "price": price})
    return json.dumps(hotels_data)
  except Exception as e:
    return "There is some error"+e





def map_location_search(location: str, search_type: str = "place") -> str:
    """
    Search for locations on Google Maps using SerpAPI

    Args:
        location: Location name/query (e.g., "restaurants in Paris", "coffee shops near me")
        search_type: Type of search - "place" for general places or "local" for local listings

    Returns:
        JSON string with location data including name, address, rating, coordinates
    """
    SERPAPI_API_KEY = userdata.get('serpapi')
    if not SERPAPI_API_KEY:
        return json.dumps({"error": "SERPAPI_API_KEY not found in Colab secrets. Please add it with the name 'test'."})

    SERPAPI_URL = "https://serpapi.com/search"

    params = {
        "engine": "google_maps",
        "q": location,
        "api_key": SERPAPI_API_KEY,
        "hl": "en",
        "gl": "us",
        "type": search_type,  # "place" or "local"
    }

    try:
        response = requests.get(SERPAPI_URL, params=params)
        response.raise_for_status()
        search_results = response.json()
        print("SerpAPI Map Search Results:", search_results)  # Debug print

        locations_data = []

        # Try to extract from 'local_results' (for local search)
        if 'local_results' in search_results:
            for place in search_results['local_results']:
                location_info = {
                    "name": place.get('title'),
                    "address": place.get('address'),
                    "rating": place.get('rating'),
                    "review_count": place.get('review_count'),
                    "type": place.get('type'),
                    "website": place.get('website'),
                    "phone": place.get('phone'),
                    "coordinates": {
                        "latitude": place.get('latitude'),
                        "longitude": place.get('longitude')
                    }
                }
                # Only add if we have at least name and address
                if location_info['name'] and location_info['address']:
                    locations_data.append(location_info)

        # Fallback to 'places' if local_results not available
        elif 'places' in search_results:
            for place in search_results['places']:
                location_info = {
                    "name": place.get('title'),
                    "address": place.get('address'),
                    "rating": place.get('rating'),
                    "review_count": place.get('review_count'),
                    "coordinates": {
                        "latitude": place.get('latitude'),
                        "longitude": place.get('longitude')
                    }
                }
                if location_info['name']:
                    locations_data.append(location_info)

        return json.dumps(locations_data, indent=2)

    except Exception as e:
        return json.dumps({"error": f"There is an error: {str(e)}"})

tools  =[flights_search_v2,hotels_search_v2,map_location_search]

# Define UDF to run with agent
def run_agent(prompt:str,tools:list):
  print(f" Your promit is : {prompt}")
  response = client.models.generate_content(model=MODEL,contents=[prompt],config=types.GenerateContentConfig(tools=tools))
  if response.function_calls:
    print(response.function_calls)
  else:
    print(response.text)

run_agent("search hotel in pune with best price for 2 night on 2026-9-22 ",tools)

